public abstract class etk
{
    public static final htk A;
    public static final htk B;
    public static final htk C;
    public static final htk D;
    public static final htk E;
    public static final htk F;
    public static final htk G;
    public static final htk H;
    public static final htk I;
    public static final htk J;
    public static final htk K;
    public static final htk L;
    public static final htk M;
    public static final htk N;
    public static final htk O;
    public static final htk P;
    public static final htk Q;
    public static final htk R;
    public static final htk S;
    public static final htk a;
    public static final htk b;
    public static final htk c;
    public static final htk d;
    public static final htk e;
    public static final htk f;
    public static final htk g;
    public static final htk h;
    public static final htk i;
    public static final htk j;
    public static final htk k;
    public static final htk l;
    public static final htk m;
    public static final htk n;
    public static final htk o;
    public static final htk p;
    public static final htk q;
    public static final htk r;
    public static final htk s;
    public static final htk t;
    public static final htk u;
    public static final htk v;
    public static final htk w;
    public static final htk x;
    public static final htk y;
    public static final htk z;
    
    static {
        a = new htk("ContentDescription", true, (zta)new o9k((byte)22));
        b = new htk("StateDescription", 0);
        c = new htk("ProgressBarRangeInfo", 0);
        d = new htk("PaneTitle", true, (zta)new dtk((byte)1));
        e = new htk("SelectableGroup", 0);
        f = new htk("CollectionInfo", 0);
        g = new htk("CollectionItemInfo", 0);
        h = new htk("Heading", 0);
        i = new htk("TextEntryKey", 0);
        j = new htk("Disabled", 0);
        k = new htk("LiveRegion", 0);
        l = new htk("Focused", 0);
        m = new htk("IsContainer", 0);
        n = new htk("IsTraversalGroup");
        o = new htk("IsSensitiveData");
        p = new htk("InvisibleToUser", (zta)new o9k((byte)28));
        q = new htk("HideFromAccessibility", (zta)new o9k((byte)28));
        r = new htk("ContentType", (zta)new dtk((byte)2));
        s = new htk("ContentDataType", (zta)new dtk((byte)3));
        t = new htk("FillableData", (zta)new dtk((byte)4));
        u = new htk("TraversalIndex", (zta)new o9k((byte)23));
        v = new htk("HorizontalScrollAxisRange", 0);
        w = new htk("VerticalScrollAxisRange", 0);
        x = new htk("IsPopup", true, (zta)new o9k((byte)24));
        y = new htk("IsDialog", true, (zta)new o9k((byte)25));
        z = new htk("Role", true, (zta)new o9k((byte)26));
        A = new htk("TestTag", false, (zta)new o9k((byte)27));
        B = new htk("LinkTestMarker", false, (zta)new o9k((byte)28));
        C = new htk("Text", true, (zta)new o9k((byte)29));
        D = new htk("TextSubstitution");
        E = new htk("IsShowingTextSubstitution");
        F = new htk("InputText", 0);
        G = new htk("EditableText", 0);
        H = new htk("TextSelectionRange", 0);
        I = new htk("TextCompositionRange", 0);
        J = new htk("ImeAction", 0);
        K = new htk("Selected", 0);
        L = new htk("ToggleableState", 0);
        M = new htk("InputTextSuggestionState", 0);
        N = new htk("Password", 0);
        O = new htk("Error", 0);
        P = new htk("IndexForKey");
        Q = new htk("IsEditable");
        R = new htk("MaxTextLength");
        S = new htk("Shape", false, (zta)new dtk((byte)0));
    }
}
